<a href="https://colab.research.google.com/github/abusayedruetcse/Deep-Learning-Specialization/blob/master/python_numpy_vectors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
a = np.random.randn(5)
print(a)

[-0.52350926 -1.83941074  0.36724476  1.17757558  0.05424052]


In [3]:
print(a.shape)

(5,)


In [4]:
print(a.T)

[-0.52350926 -1.83941074  0.36724476  1.17757558  0.05424052]


In [5]:
print(a.T.shape)

(5,)


In [6]:
print(np.dot(a,a.T))

5.181988795871099


don't use like previous shape (5, ) or ( ,5)

In [7]:
a = np.random.randn(5,1)
print(a)

[[-0.62523954]
 [ 0.39570219]
 [ 0.48669115]
 [-1.04394448]
 [-1.73314987]]


In [8]:
print(a.T)
print(a.T.shape)

[[-0.62523954  0.39570219  0.48669115 -1.04394448 -1.73314987]]
(1, 5)


In [9]:
print(np.dot(a,a.T))

[[ 0.39092448 -0.24740865 -0.30429855  0.65271536  1.08363383]
 [-0.24740865  0.15658022  0.19258475 -0.41309111 -0.6858112 ]
 [-0.30429855  0.19258475  0.23686828 -0.50807854 -0.84350871]
 [ 0.65271536 -0.41309111 -0.50807854  1.08982007  1.80931223]
 [ 1.08363383 -0.6858112  -0.84350871  1.80931223  3.00380847]]


=> Use (5,1) or (1,5) instead of (5) means (5,) : (5,1) or (1,5) has [[ ]] but in (5) has []
